### ISSUE TITLE
No stm32cubeide project for the STM32H7S78-DK BSP project.

### ISSUE THREAD

**Issue by AndrewCapon** [STMicroelectronics/STM32CubeH7RS#1]
Hi Guys,

There is only EWARM available in https://github.com/STMicroelectronics/STM32CubeH7RS/tree/main/Projects/STM32H7S78-DK/Examples/BSP.

Is there a way of importing this into stm32cubeide?

Many thanks

Andy

**Comment by TOUNSTM** [comment]
Hello @AndrewCapon,

Thank you for your contribution. You are absolutely right about this point.
Actually, the point you raised has been implemented and is now available in the frame of the latest STM32CubeH7RS package, version V1.1.0 . This issue can be closed now. Thank you again for your contribution.

With regards,
