### ISSUE TITLE
There is no demonstration folder

### ISSUE THREAD

**Issue by corero2** [STMicroelectronics/STM32CubeH7RS#3]
Is the demonstration folder anywhere, or any clue when will be added?

**Comment by ALABSTM** [comment]
Hi @corero2,

There is no demo folder indeed as there is no demo published within the firmware so far. I'll ask more about this point and let you know as soon as I have new info.

With regards,

**Comment by ALABSTM** [comment]
Hi @corero2,

The development teams just confirmed that there will be no demo folder within the STM32CubeH7RS firmware.

Please allow me to close this thread. Thank you for your comprehension.

With regards,
