### ISSUE TITLE
USBD MSC does not support more than 2 luns

### ISSUE THREAD

**Issue by xu-yingjing** [STMicroelectronics/STM32CubeH7RS#4]
Hello,

In the function MSC_BOT_CBW_Decode() of the file usbd_msc_bot.c, there is the following judgment:

```C
  if ((USBD_LL_GetRxDataSize(pdev, MSCOutEpAdd) != USBD_BOT_CBW_LENGTH) ||
      (hmsc->cbw.dSignature != USBD_BOT_CBW_SIGNATURE) ||
      (hmsc->cbw.bLUN > 1U) || (hmsc->cbw.bCBLength < 1U) ||
      (hmsc->cbw.bCBLength > 16U))
  {
    SCSI_SenseCode(pdev, hmsc->cbw.bLUN, ILLEGAL_REQUEST, INVALID_CDB);

    hmsc->bot_status = USBD_BOT_STATUS_ERROR;
    MSC_BOT_Abort(pdev);
  }
  else
  {
    /* ... */
  }
```

As shown in the above code, when **(hmsc->cbw.bLUN > 1U)** is established, it will be judged as an illegal request. Therefore, the legal value of **hmsc->cbw.bLUN** can only be 0 or 1. For this reason, USBD MSC can only support a maximum of 2 luns.

Why not add a MSC configuration macro definition in the file usbd_conf_template.h to configure the maximum number of luns supported?

**Comment by ALABSTM** [comment]
See also [STM32CubeL4#41](https://github.com/STMicroelectronics/STM32CubeL4/pull/41)

**Comment by ALABSTM** [comment]
ST Internal Reference: 126925

**Comment by ALABSTM** [comment]
Hi @xu-yingjing,

Our development teams acknowledged your request and agreed with the principle. However, there is currently no plan to address it. I will keep you informed should there be any news.

The request has been already logged internally. It will be tracked on GitHub via [this](https://github.com/STMicroelectronics/STM32CubeL4/pull/41) issue (mentioned above). Please allow me to close this one. Thank you for your comprehension.

With regards,
